### ISSUE TITLE
Admin Log page error

### ISSUE THREAD

**Issue by vafrcor** [Laravel-Backpack/LogManager#22]
# Bug report

### What I did:
- Install based on https://laravel-backpack.readme.io/docs/install-on-laravel-55#section-6-logmanager
- Open admin-dashboard for `log` page.

### What I expected to happen:
- seeing this preview https://camo.githubusercontent.com/4a63b8a2cbbde310bde171272a954720c121b777/68747470733a2f2f6261636b7061636b666f726c61726176656c2e636f6d2f75706c6f6164732f73637265656e73686f74732f6c6f675f6c6973742e706e67

### What happened:
An error from Whoops as below:
```
[2018-03-13 00:58:38] local.ERROR: Driver [] is not supported. {"userId":1,"email":"example@gmail.com","exception":"[object] (InvalidArgumentException(code: 0): Driver [] is not supported. at /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php:127)
[stacktrace]
#0 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(103): Illuminate\\Filesystem\\FilesystemManager->resolve('storage')
#1 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(80): Illuminate\\Filesystem\\FilesystemManager->get('storage')
#2 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Filesystem\\FilesystemManager->disk('storage')
#3 /Applications/MAMP/htdocs/private/backpack/vendor/backpack/logmanager/src/app/Http/Controllers/LogController.php(15): Illuminate\\Support\\Facades\\Facade::__callStatic('disk', Array)
#4 [internal function]: Backpack\\LogManager\\app\\Http\\Controllers\\LogController->index()
#5 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#6 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#7 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Backpack\\LogManager\\app\\Http\\Controllers\\LogController), 'index')
#8 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#9 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Route->run()
#10 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Applications/MAMP/htdocs/private/backpack/vendor/backpack/base/src/app/Http/Middleware/Admin.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Backpack\\Base\\app\\Http\\Middleware\\Admin->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#35 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#36 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#37 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#38 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Applications/MAMP/htdocs/private/backpack/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /Applications/MAMP/htdocs/private/backpack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 /Applications/MAMP/htdocs/private/backpack/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 {main}
"} 
```

### What I've already tried to fix it:
- i don't understand the solution

### Backpack, Laravel, PHP, DB version:
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.1.3",
        "backpack/backupmanager": "^1.3",
        "backpack/base": "^0.8.9",
        "backpack/crud": "^3.3",
        "backpack/langfilemanager": "^1.0",
        "backpack/logmanager": "^2.3",
        "backpack/pagemanager": "^1.1",
        "backpack/settings": "^2.0",
        "fideloper/proxy": "~4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "backpack/generators": "^1.1",
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "laracasts/generators": "dev-master",
        "mockery/mockery": "~1.0",
        "nunomaduro/collision": "~2.0",
        "phpunit/phpunit": "~7.0",
        "symfony/thanks": "^1.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by tabacitu** [comment]
Hi @vafrcor ,

Are you sure you've done [step 2 of the installation process](https://laravel-backpack.readme.io/docs/install-on-laravel-55#section-6-logmanager)?

Cheers!

**Comment by vafrcor** [comment]
Hi @tabacitu ,
Step-2 process is finished without any problem and i have already follow all instruction.

The main problem is about log driver not configured correctly by this package.
any clue ?

**Comment by vafrcor** [comment]
Hi @tabacitu,
After I re-check your docummentation (https://laravel-backpack.readme.io/docs/install-on-laravel-55#section-6-logmanager), I think your explanation is missing `sub-config` about `disk` just like at Backup-manager (https://laravel-backpack.readme.io/docs/install-on-laravel-55#section-5-backupmanager).

Please see attachment for details. 

![backpack-4-laravel-logmanager-setup](https://user-images.githubusercontent.com/2148366/37743324-2fa050fe-2d9c-11e8-8967-b762cf352cd5.png)
![backpack-4-laravel-backupmanager-setup](https://user-images.githubusercontent.com/2148366/37743432-9d8b6bd0-2d9c-11e8-8767-b2f8bb02fb4c.png)

**Comment by tabacitu** [comment]
Hi @vafrcor ,

Thanks for the update, but I'm afraid I don't understand. What do you mean by that? What's missing?

I've modified the description in the docs, to make it clearer that you need to add a **disk**. I've installed it myself a couple of times to make sure it's working and it seems to be working fine for me, AFTER I do step no 2 in the installation (adding the storage disk).

Thanks, cheers!
